"use client"

import { formatMinutesAsHoursMinutes } from "@/lib/calculations/driving-segments"
import { calculateProgress } from "@/lib/calculations/progress"
import { Button } from "@/components/ui/button"
import { Printer } from "lucide-react"
import type { DrivingSessionRow, ProfileRow, SupervisorRow } from "@/types/database"

interface LogbookExportViewProps {
  sessions: DrivingSessionRow[]
  supervisorsById: Record<string, SupervisorRow>
  profile: ProfileRow | null
}

export function LogbookExportView({ sessions, supervisorsById, profile }: LogbookExportViewProps) {
  const progress = calculateProgress(
    sessions.map((s) => ({ date: s.session_date, dayMinutes: s.day_minutes, nightMinutes: s.night_minutes }))
  )

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between print:hidden">
        <h1 className="text-lg font-semibold">Export logbook</h1>
        <Button onClick={() => window.print()} className="gap-2">
          <Printer className="size-4" />
          Print / Save PDF
        </Button>
      </div>

      <div className="rounded-lg border bg-background p-5 print:border-0 print:p-0">
        <header className="mb-4 border-b pb-4">
          <h2 className="text-xl font-bold">Learner Driving Log — South Australia</h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Learner-generated record, not an official South Australian Government document.
          </p>
          <div className="mt-3 grid grid-cols-2 gap-2 text-sm">
            <div>
              <span className="text-muted-foreground">Learner: </span>
              {profile?.full_name ?? profile?.email ?? "—"}
            </div>
            <div>
              <span className="text-muted-foreground">Permit date: </span>
              {profile?.permit_date ?? "—"}
            </div>
            <div>
              <span className="text-muted-foreground">Total hours: </span>
              {formatMinutesAsHoursMinutes(progress.totalMinutes)} / 75h
            </div>
            <div>
              <span className="text-muted-foreground">Night hours: </span>
              {formatMinutesAsHoursMinutes(progress.nightMinutes)} / 15h
            </div>
          </div>
        </header>

        <table className="w-full border-collapse text-xs">
          <thead>
            <tr className="border-b text-left">
              <th className="py-1.5 pr-2">Date</th>
              <th className="py-1.5 pr-2">Start</th>
              <th className="py-1.5 pr-2">End</th>
              <th className="py-1.5 pr-2">Duration</th>
              <th className="py-1.5 pr-2">From → To</th>
              <th className="py-1.5 pr-2">Conditions</th>
              <th className="py-1.5 pr-2">Supervisor</th>
              <th className="py-1.5 pr-2">Confirmed</th>
            </tr>
          </thead>
          <tbody>
            {sessions.map((s) => (
              <tr key={s.id} className="border-b align-top">
                <td className="py-1.5 pr-2 whitespace-nowrap">{s.session_date}</td>
                <td className="py-1.5 pr-2">{s.start_time.slice(0, 5)}</td>
                <td className="py-1.5 pr-2">{s.end_time.slice(0, 5)}</td>
                <td className="py-1.5 pr-2 whitespace-nowrap">{formatMinutesAsHoursMinutes(s.total_minutes)}</td>
                <td className="py-1.5 pr-2">
                  {s.starting_location} → {s.destination}
                </td>
                <td className="py-1.5 pr-2">
                  {s.weather_condition} / {s.road_condition} / {s.traffic_condition}
                </td>
                <td className="py-1.5 pr-2">
                  {s.supervisor_id ? supervisorsById[s.supervisor_id]?.name ?? "—" : "—"}
                </td>
                <td className="py-1.5 pr-2">
                  {s.learner_confirmed && s.supervisor_confirmed ? "Yes" : "No"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <footer className="mt-6 border-t pt-4 text-[10px] text-muted-foreground">
          Generated by a personal record-keeping app, not the South Australian Government. Verify
          current logbook submission requirements at mylicence.sa.gov.au before relying on this
          document for a provisional licence application.
        </footer>
      </div>
    </div>
  )
}
